version: "3.8"

services:
  code-editor:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-nest/editor
    ports:
      - "5000:5000"  # Backend port mapping
      - "3000:3000"  # Frontend port mapping
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - SERVER_PORT=5000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
